### PR TITLE
Viz product infrastructure

### LINKED ISSUE #345: Update pipeline to publish multiple map services from the same workflow
The high level requirement is that we need to be able to publish multiple maps from a single workflow. For example, the ana_inundation workflow needs to be able to publish a public map with only the extent and a noaa internal map that has the extent and QC FIM layer group. A proposed setup is shown before where we have an overall configuration that is reference to the NWM forecast type. Within a configuration we can have multiple products which is a reference to how we are going to process data. Within a product we can have multiple maps which is a reference to how the data will be displayed

proposed_configuration_example

### LINKED ISSUE #373: Move max flows lambda into step function
The max flows and the initialize pipeline function are duplicating code with the pipeline class now. It would be good to just put that in the shared funcs/viz classes code

### PR DESCRIPTION
**Pull request by CoreyKrewson-NOAA**
Large update to the processing pipelines which mainly moves away from the DB admin tables and allows multiples services to be published from the same product. 

## Additions

- Introduction of the product concept which is processed data from the raw inputs
- New YAML files in the initialize pipeline function will handle pipeline products and as well as derived services from the product
- New YAML files in the publish function which handle the service metadata
- Separate Step Function folder for TF

## Removals

- Dependency on the admin DB table for data flows and service metadata

## Changes

- Max flows function is now generalized and called Max Values
- Separate fim_configs folder in the postprocess function
- Tweaks to step function which include adding a lambda max flows map before the DB ingest, changing some inputs/outputs between step function actions, and changing fim config outputs to point to sql postprocessing

## Screenshots

stepfunctions_graph

### CODE REVIEW

**Review by shawncrawley — DISMISSED** [review]
This all looks great from what I was able to comb through. The proof will be in the pudding - which I'm excited to sample. Bon Appetit!

**Comment by shawncrawley** [comment]
Still looks good.

**Comment by CoreyKrewson-NOAA** [comment]
ok @shawncrawley I think this is good to go now. 

@nickchadwick-noaa After Shawn's review I think we are good to merge. Everything seems to be working well from the testing as far as I can tell

**Review by shawncrawley — APPROVED** [review]
Good to go by me!

**Pull request merged**
