### PR TITLE
Hand FIM improvements

### LINKED ISSUE #998: Solve Alaska HAND FIM Processing Memory bottleneck
Weeks ago while first testing Alaska FIM, we came face to face with the fact that the underlying inputs for creating HAND FIM polygons for Alaska are too large. They surpass the maximum memory that can be allocated to the hv-vpp-*-viz-hand-fim-processing Lambda.

Here are the priorities we identified as steps for solution to getting Alaska FIM working as services:

* Taking reprojection out of lambda running processing
* Running the GMS only
* Run for just Anchorage AK to get a rapid solution

Here are the longer term solutions to get a stable pipeline for the service after we get something available for Workshop:

* Have Ryan look into HAND Processing code for efficiencies
* Setup running on smaller HUC 10 domains for Alaska
* Filter out smaller stream orders (whether in GMS or branch 0 depending on other tests)

Getting a service up to UAT is the primary goal, the next will be getting the service stable and tested fully for all the services in UAT, then lastly before pushing is making any budgetary efficiency measurements on the service.

### PR DESCRIPTION
**Pull request by groutr**
The biggest change is selective column loading for csv files. This could potentially significantly reduce memory usage.

The rest of the changes are relatively minor.
* np.where(condition) is an inefficient way of masking an array. It's about 2x slower and allocates an extra array.
* sorting values is not an efficient way to find the max.
...and other minor fixes that simplify the code.

### CODE REVIEW

**Comment by RobHanna-NOAA** [comment]
We might want to double check which fields from the that table show up in the UI. There may be UI columns that the field want to see.  Update here on what you find as I can take it back to FIM-Dev and find out why they are submitting those columns to HV.

**Comment by groutr** [comment]
I'm not sure I understand what you mean. The code is not discarding any columns that were not already being discarded.

**Comment by RobHanna-NOAA** [comment]
doh.. on nothing. I am a dork. I was mis-reading the FIM-dev input dataset.  :)

**Review by shawncrawley — APPROVED** [review]
Looks good - thank you!

**Pull request merged**
