### PR TITLE
added EXPERIMENTAL label to publicly available FIM layers

### LINKED ISSUE #524: Add "EXPERIMENTAL" label to publicly available FIM layers
Add the following to the three public FIM layer names:

Inundation Extent (EXPERIMENTAL)
5 Days - Inundation Extent (EXPERIMENTAL)
5 Days - RFC Inundation Extent (EXPERIMENTAL)

And update service descriptions with text provided by Fernando Salas

### PR DESCRIPTION
**Pull request by KatherinePowell-NOAA**
Added/edited the following labels to the three public FIM layers - mapx and yml files:

ana_inundation_extent:
"Inundation Extent (EXPERIMENTAL)"

mrf_gfs_5day_max_inundation_extent:
"5 Days - Inundation Extent (EXPERIMENTAL)"

rfc_based_5day_max_inundation_extent:
"5 Days - Inundation Extent (EXPERIMENTAL)"

### CODE REVIEW

**Comment by CoreyKrewson-NOAA** [comment]
Thanks Katherine. Because the EC2s are using an older version of Pro, these updates may cause some issues. Can you keep the mapx how it was before and just update the layer name?

**Comment by KatherinePowell-NOAA** [comment]
Do you mean just edit the mapx file in a text editor and not in ArcGIS Pro?

**Comment by CoreyKrewson-NOAA** [comment]
yep, that is probably the best way to do it without having to get onto an EC2

**Comment by KatherinePowell-NOAA** [comment]
OK, I restored the mapx files, then edited the label directly through a text editor, outside of arcgis pro software.

**Review by CoreyKrewson-NOAA — APPROVED** [review]

**Comment by CoreyKrewson-NOAA** [comment]
Thanks. Looks great.

**Pull request merged**
