### PR TITLE
PSURGE coastal FIM extent sublayers implemented

### LINKED ISSUE #347: SCHISM - Develop workflow to handle PSURGE datasets when available
When hurricane threats are present, NWM 3.0 will process new datasets using the PSURGE coastal model. These datasets will be in addition to the normal coastal output that are produced daily (using the ESTOFS coastal model). We need to figure out a way to process the additional PSURGE coastal model when present. Along with that we need to decide how we present this information. Do we create a standalone service just for that? Do we republish the existing with a new PSURGE layer?

### LINKED ISSUE #368: Update pipeline to process optional files
When there is a hurricane event going on, the NWM v3.0 will produce additional coastal files from the PSURGE model (the standard daily files are created from the STOFS model). We need to update the pipeline process to check for and process optional files. This way we can set the service to run PSURGE whenever it becomes available automatically.

### LINKED ISSUE #369: Update workflow to dynamically add new layers to map from pipeline
When there is a hurricane event going on, the NWM v3.0 will produce additional coastal files from the PSURGE model (the standard daily files are created from the STOFS model). 

Once we get the geoprocessing tool for publishing to work, we will also need to be able to add layers or data to the maps dynamically to mapx docs. This will give us the ability to add the PSURGE data to the map automatically without having to have a new map or do any manual work during an event.

### PR DESCRIPTION
**Pull request by shawncrawley**
This implements the PSURGE coastal inundation sublayers to the SRF and MRF coastal inundation products. This involved adding an additional "fim_config" entry for each of these product configs to handle the PSURGE data. The things that make this FIM configuration different than the others in the same product config is that: 1) there is a new `"optional": true` key/value pair under the "preprocess" section, and 2) there is a "postprocess" section. 

The new `optional` keyword only applies to the `fim_configs -> preprocess` section - as it is only checked and responded to in the `viz_max_values` lambda that deals with creating a max_elevs file. This of course trickles down to affecting the behavior of the `viz_schism_fim_processing` function as well. Namely, this function will now create an empty raster (i.e. 0s in every cell) for any huc that is missing any of the key inputs - which in this case would be the max_elevs file, but this also extends to other dataset issues, such as the total_water forecast not including any points within the specific huc. An empty raster will produce no extent polygons.

To handle the workflow case where PSURGE files don't exist and thus no extent polygons are created (i.e. the ingest table is empty), I implemented the `postprocess` section mentioned in the first paragraph. The SQL executed inserts a dummy row of data into the table before copying it into the publish schema (and adds the `update_time` attribute). Thus, there will always be at least one row of data that can return this `update_time` to reassure users that there truly is no PSURGE data and that the sublayer is not just broken.

**Two important notes:**
* I haven't implemented any retry mechanism in the case of marking the fim_config preprocessing as "optional". This does seem like an important thing to implement, but I feel it may be partially unnecessary in this particular case if the PSURGE files always show up before the non-PSURGE files. On a similar note, namely that we don't yet know the timing of the PSURGE files, it would be nice to decide how to implement a retry once the timing is known.
* I have another PR open right now (#486) that includes changes that have implications for this pull request as well. Namely, that pull request implemented the coastal depth services as VRTs. We will want to add a PSURGE VRT sublayer to those services as well once that pull request is merged.

**Due to both of the above, this pull request should be treated only as a draft for now and is not suitable for merging into TI.**

### CODE REVIEW

**Comment by CoreyKrewson-NOAA** [comment]
@shawncrawley Should we also have an AnA version for the optional psurge configuration?

**Comment by shawncrawley** [comment]
Not according to this [Service Change Notice](https://docs.google.com/document/d/16TTzGP3Up7X_bf1OnREsSIhZAJMhTPsN9e_JbtkiBF8/edit) that Brian Cosgrove pointed us to. It only shows up with short range and medium range there.

**Comment by CoreyKrewson-NOAA** [comment]
@shawncrawley ah cool. good catch. I'll go ahead and approve/merge this then if it is ready.

**Comment by shawncrawley** [comment]
Ah wait, I just re-read my comments above and realized I haven't done those two things! Let me jump in now and hurry and get those done, I'll let you know when ready.

**Comment by shawncrawley** [comment]
I just pushed the additional updates. Let me know if this looks too messy, but I added a "Catch" condition after the MissingS3FileException retries to ultimately check if "optional" is included, and if so it just moves on. Otherwise, it fails. Here's what that looks like at the high-level view:
image

**Comment by CoreyKrewson-NOAA** [comment]
Looks good to me. My only question is handling the map layers/data when this happens. Does the table truncating happen in the fim config preprocessing or the fim data preparation? I can't remember when that happens but we would want to clean up the table before potentially processing the data right? That way the service shows an empty table because no new data has been provided for an optional file?

**Comment by shawncrawley** [comment]
The table truncating for the inundation extent layer happens in the fim_data_prep lambda - and the table now always gets populated with a dummy row to allow querying of the update_time. As per the depth layer, an empty raster will get created, overwriting the previous, if there is no max_elevs file.

**Comment by CoreyKrewson-NOAA** [comment]
ah I see. I was misreading the workflow. Sounds good to me.

**Review by CoreyKrewson-NOAA — APPROVED** [review]

**Pull request merged**
