### PR TITLE
Pipeline Fixes

### PR DESCRIPTION
**Pull request by CoreyKrewson-NOAA**
This PR resolves a couple issues from #539 and #543 

- Just to stay consistent with the TF, I renamed the actual max-values lambda to python-preprocessing
- I updated the zip file for the python preprocessing lambda to zip up the whole folder (including the products folder) instead of just the lambda handler
- I fixed the reference in the step function json to point to configuration_data_flow.python_preprocessing (new key) instead of configuration_data_flow.lambda_max_flows (old key)

- I updated the schism lambda function to get the domain from the max_file name instead of the fim_config name. The fim_config name shortens the domain (i.e. hi instead of hawaii) and so the correct domain could not be parsed from the fim config name
- I also added a setup_db_table function to the schism fim processing lambda to clean the table for every run. The DB was not being cleaned after each run and thus rows just kept being added to it. 

Additionally, I removed the dmf (database max flows) prefix from the pipelines when the configuration wants to be ran in 2 separate step functions (pipelines with python preprocessing and those without). The dmf was just confusing and by removing it, the name for the normal non python processing will stay consistent with the other pipeline runs. Now if there is a special pipeline run for products that need python preprocessing, there will just be 1 special run name that has ppp (python preprocessing)

For example, now there are 2 SRF runs such as 
- sns_srf_20231002T1400
- sns_ppp_srf_20231002T1400

### CODE REVIEW

**Review by shawncrawley — DISMISSED** [review]
Looks good!

**Comment by CoreyKrewson-NOAA** [comment]
I added one more update to the schism fim lambda that was causing issues.

**Review by shawncrawley — DISMISSED** [review]
Looks good. I should've been the one to get that setup_db_table function in there - thanks for catching that for me.

**Review by shawncrawley — APPROVED** [review]
Good to go.

**Pull request merged**
